### ISSUE TITLE
gate.sh: shell-level fixture for the two-sided ci.fusecheck bound (legacy, MIN MAX, =N, malformed, hard-fail)

### ISSUE THREAD

**Issue by shaiss** [shaiss/print-bench#627]
Follow-up from the Copilot review of #618 (the two-sided `ci.fusecheck` assert).

## The gap

`tools/printcheck`'s pytest suite pins `fusecheck --bound` and the pure bound logic, and the six designs that ship a `ci.fusecheck` today exercise the **legacy** `assert <stl> <min>` path live on every CI run. But the parsing seam in `gate.sh` itself — the `read` tokenisation of `assert <stl> <min> [<max>]` / `assert <stl> =N`, and the mapping of `fusecheck`'s exit codes 3 (too few) / 4 (too many) onto WARN vs hard FAIL — has no shell-level test. A regression there could leave every current test green while a real manifest accepts a freed island or mishandles a two-sided bound.

## Ask

An end-to-end fixture in the mold of `scripts/kinematics-fixtures/` (#620): a tiny fixture design with a separable two-body part and a known-fused one, and manifests covering

- legacy `assert <stl> <min>` (passes / WARNs when fused),
- `assert <stl> <min> <max>` (passes inside the bound, hard-FAILs above `max`),
- `assert <stl> =N` (exact),
- a malformed bound (`max < min`, non-numeric) → the malformed-line FAIL,
- the hard-fail exit path (exit 4 → FAIL, never WARN),

run as a `gate.sh --fusecheck-selftest` (or a `scripts/fusecheck-check.sh --selftest`) that `check.sh` calls, with every negative row asserted to fire.

## Why not in #618

The review landed at the end of a time-boxed overnight sprint; the two other findings on that PR (width-helper guards, the automated tether proof) shipped in `e555a8a`. This one is a test-coverage addition with its own fixture surface, so it is tracked here rather than widening #618 after its evidence was posted.

Refs #612, #618.

**Comment by shaiss** [comment]
🚢 SHIP-LOCK — shipping this as one PR.

**Chosen approach:** the issue's second named form — a dedicated `scripts/fusecheck-check.sh --selftest` that `check.sh` calls (matching the repo's existing `*-check.sh --selftest` convention), driving the **real** `gate.sh` fusecheck pass end-to-end over committed fixture manifests in a new `scripts/fusecheck-fixtures/` directory, the mold of `scripts/kinematics-fixtures/` (#620) — not a new `--fusecheck-selftest` flag inside `gate.sh`. The two forms are behaviorally identical in the issue's own framing ("or"); the dedicated script is picked for convention-fit.

**Acceptance criteria** (done = every box checked, verified not asserted)
- [ ] AC1 — fixtures: a tiny fixture design renders a **separable two-body** part and a **known-fused** one (plus whatever third shape the above-max row needs); body counts verified by running `fusecheck` on the exported STLs directly, so the manifest expectations are anchored to measured geometry, not to what the harness reports.
- [ ] AC2 — legacy `assert <stl> <min>`: passes on the separable part; **WARNs** (exit 3, too few) on the fused part — the run continues.
- [ ] AC3 — two-sided `assert <stl> <min> <max>`: passes inside the bound; **hard-FAILs** (exit nonzero) when the count exceeds `max`.
- [ ] AC4 — `assert <stl> =N`: exact-count row passes at N.
- [ ] AC5 — malformed bounds (`max < min`, and a non-numeric operand): the malformed **line itself** FAILs the manifest parse.
- [ ] AC6 — exit-code mapping pinned both directions by the rows above: exit 3 (too few) is never a hard FAIL, exit 4 (too many) is never downgraded to WARN.
- [ ] AC7 — `check.sh` runs the selftest, and every negative row is asserted to fire: the selftest exits nonzero if any expected WARN / FAIL / malformed-FAIL verdict fails to occur (negative controls in the #620 mold, not just happy-path greens).

**Touches:** `scripts/fusecheck-check.sh` (new), `scripts/fusecheck-fixtures/**` (new — fixture `.scad`, manifests, README), `scripts/check.sh`, `CLAUDE.md` (the `scripts/` bullet — `docs-check.sh` requires it to name every file in `scripts/`)

**Explicitly not in scope:** any change to `tools/printcheck`'s fusecheck logic itself (a defect found while building this gets a new issue, linked from the PR — this PR adds tests only); the six existing designs' `ci.fusecheck` manifests; `gate.sh`'s runtime behavior (exercised read-only); the kinematics fixtures.

**Comment by shaiss** [comment]
**Contract amendment (non-material — base, not deliverable):** the seam this fixture tests — the `assert <stl> <min> [<max>]` / `=N` tokenisation and the exit-3/exit-4 mapping — lives on open PR **#618** (`claude/issue-612-stencil-fusecheck`), not on `main` (main's gate.sh still carries the legacy one-sided assert only, and `scripts/kinematics-fixtures/` likewise only exists on open PR #620). Since the issue itself files this as "tracked here rather than widening #618", the PR is **stacked on #618's head** (`base: claude/issue-612-stencil-fusecheck`), the repo's established pattern for sequenced work (#628→#621→#605); it retargets to `main` when #618 merges. Every AC is unchanged.

**Comment by shaiss** [comment]
📋 **Contract amendment (non-material)** — the deliverable is unchanged; two files the diff touches sit outside the posted \`Touches\` globs and are being added to them.

The contract's [Touches](https://github.com/shaiss/print-bench/issues/627#issuecomment-5655577009) listed \`scripts/fusecheck-check.sh\`, \`scripts/fusecheck-fixtures/**\`, \`scripts/check.sh\`, \`CLAUDE.md\`. Two more files change as direct consequences of that same approach:

- **\`scripts/gate.sh\`** — the chosen approach is "extract the runner into \`scripts/fusecheck-check.sh\`"; the extraction's other half is the 166-line deletion in gate.sh plus the call that replaces it. Not a deliverable change: the extracted block moved verbatim, and base-vs-branch gate logs were compared on \`captive-spinner\` (identical excluding OpenSCAD \`Total rendering time\` lines) and \`sweetheart-hamster\` (differing only in timing lines and one printcheck \`Thinnest sampled wall\` line — a base-vs-base rerun is confirming that line wobbles on identical code too, i.e. re-render tessellation, not the extraction). Full evidence lands in the PR's scope-audit table.
- **\`README.md\`** — \`scripts/docs-check.sh\` fails a PR that adds a file under \`scripts/\`\` without naming it in README's scripts list, so the \`fusecheck-check.sh\` bullet is forced by the docs-drift gate (same reason \`CLAUDE.md\` was already listed).

\`Touches\` is therefore read as also covering \`scripts/gate.sh\` and \`README.md\`. No AC changes.

**Comment by shaiss** [comment]
🚢 SHIP-LOCK — shipping this as one PR.

**Taking over the stale claim** ([posted 2026-09-13T19:31:49Z](https://github.com/shaiss/print-bench/issues/627#issuecomment-5655577009), last amended 20:22Z): ~11 h old, no `claude/issue-627-*` branch on the remote, no open PR closing this issue — a run that died after amending its contract but before pushing a branch. Its contract was frozen on this thread before any diff existed, so it is re-frozen below **unchanged**, with both posted amendments ([stack on #618](https://github.com/shaiss/print-bench/issues/627#issuecomment-5655598055), [Touches widened to `scripts/gate.sh` + `README.md`](https://github.com/shaiss/print-bench/issues/627#issuecomment-5655742973)) folded in.

**Chosen approach:** the issue's second named form — a dedicated `scripts/fusecheck-check.sh --selftest` that `check.sh` calls (matching the repo's existing `*-check.sh --selftest` convention), driving the **real** `gate.sh` fusecheck pass end-to-end over committed fixture manifests in a new `scripts/fusecheck-fixtures/` directory, the mold of `scripts/kinematics-fixtures/` (#620) — not a new `--fusecheck-selftest` flag inside `gate.sh`. The two forms are behaviorally identical in the issue's own framing ("or"); the dedicated script is picked for convention-fit. The parsing seam moves with it: the fusecheck runner is **extracted** from `gate.sh` into `scripts/fusecheck-check.sh` verbatim, and `gate.sh` calls the extracted runner — so the selftest exercises the one parser `gate.sh` actually runs, not a copy of it (a selftest over a copy could stay green while the seam regressed, which is exactly the gap this issue files).

**Acceptance criteria** (done = every box checked, verified not asserted)
- [ ] AC1 — fixtures: a tiny fixture design renders a **separable two-body** part and a **known-fused** one (plus whatever third shape the above-max row needs); body counts verified by running `fusecheck` on the exported STLs directly, so the manifest expectations are anchored to measured geometry, not to what the harness reports.
- [ ] AC2 — legacy `assert <stl> <min>`: passes on the separable part; **WARNs** (exit 3, too few) on the fused part — the run continues.
- [ ] AC3 — two-sided `assert <stl> <min> <max>`: passes inside the bound; **hard-FAILs** (exit nonzero) when the count exceeds `max`.
- [ ] AC4 — `assert <stl> =N`: exact-count row passes at N.
- [ ] AC5 — malformed bounds (`max < min`, and a non-numeric operand): the malformed **line itself** FAILs the manifest parse.
- [ ] AC6 — exit-code mapping pinned both directions by the rows above: exit 3 (too few) is never a hard FAIL, exit 4 (too many) is never downgraded to WARN.
- [ ] AC7 — `check.sh` runs the selftest, and every negative row is asserted to fire: the selftest exits nonzero if any expected WARN / FAIL / malformed-FAIL verdict fails to occur (negative controls in the #620 mold, not just happy-path greens).

**Touches:** `scripts/fusecheck-check.sh` (new), `scripts/fusecheck-fixtures/**` (new — fixture `.scad`, manifests, README), `scripts/check.sh`, `scripts/gate.sh` (the extraction + the call that replaces it), `CLAUDE.md` (the `scripts/` bullet — `docs-check.sh` requires it to name every file in `scripts/`), `README.md` (the scripts list — same docs-drift gate)

**Explicitly not in scope:** any change to `tools/printcheck`'s fusecheck logic itself (a defect found while building this gets a new issue, linked from the PR — this PR adds tests only); the six existing designs' `ci.fusecheck` manifests; `gate.sh`'s runtime behavior beyond the verbatim extraction (exercised read-only); the kinematics fixtures.

**Base:** stacked on open PR **#618**'s head (`claude/issue-612-stencil-fusecheck`) — the two-sided/`=N` seam this fixture tests only exists there, not on `main`; retargets to `main` when #618 merges.

**Comment by shaiss** [comment]
📋 **Contract amendment (non-material)** — one more file the diff touches, same class as the last amendment: **`.github/workflows/ci.yml`**.

`check.sh` now calls `scripts/fusecheck-check.sh --selftest` (AC7), which drives the real runner — and the runner measures geometry through `python3 -m printcheck.fusecheck`. The two CI jobs that run `check.sh` (`scad-check`, `scad-check-nightly`) install openscad + xvfb but **not** printcheck (only `render-gate` and `printcheck-tests` do). An unconditional selftest there would be red on every PR — and a *skipped* selftest is exactly the silent green this issue exists to close, so the fix is the install, not the skip: both scad-check jobs gain `actions/setup-python` + `pip install -e tools/printcheck` (the same steps `render-gate` already carries). No AC changes; the deliverable is unchanged, only the environment that verifies it.

**Comment by shaiss** [comment]
🚢 SHIP-LOCK WITHDRAWN — scheduled run died before delivering

Wright (bench pulse 2026-09-14): no `claude/issue-627-*` branch, no closing PR. Latest claim was the 2026-09-14T06:25Z takeover (plus 06:44Z amendment). Backlog-burn run https://github.com/shaiss/print-bench/actions/runs/34813227347 walked /ship-issue with outcome `success` but produced neither artifact.

Lock cleanup did **not** withdraw: the ship walk checked out PR #618's branch (`claude/issue-612-stencil-fusecheck`) to stack, so `./scripts/routine-lock-cleanup.sh` ran the **pre-#538** copy on that branch (`::notice::agent outcome 'success' — no orphaned lock to release`). Main's artifact-derived cleanup never ran. The red gate on main's workflow then failed the job as designed.

This comment releases the claim so the next burn can re-select. Not a decline of #627 itself.

- routine: backlog-burn (manual withdrawal)
- agent outcome (diagnostic only): success
- run: https://github.com/shaiss/print-bench/actions/runs/34813227347

**Comment by shaiss** [comment]
🚢 SHIP-LOCK — shipping this as one PR.

**Taking over after the withdrawal** ([claim posted 2026-09-14T06:25:50Z](https://github.com/shaiss/print-bench/issues/627#issuecomment-5683863213), [withdrawn 12:54Z](https://github.com/shaiss/print-bench/issues/627#issuecomment-5688607463) when the scheduled run died without pushing a branch). No `claude/issue-627-*` branch, no open closing PR — the issue is free. The contract below was frozen on this thread before any diff existed and is re-frozen **unchanged**, all three posted amendments folded in ([stack on #618](https://github.com/shaiss/print-bench/issues/627#issuecomment-5655598055), [Touches widened to `scripts/gate.sh` + `README.md`](https://github.com/shaiss/print-bench/issues/627#issuecomment-5655742973), [`.github/workflows/ci.yml` added](https://github.com/shaiss/print-bench/issues/627#issuecomment-5683925491)).

**Chosen approach:** the issue's second named form — a dedicated `scripts/fusecheck-check.sh --selftest` that `check.sh` calls (matching the repo's existing `*-check.sh --selftest` convention), driving the **real** `gate.sh` fusecheck pass end-to-end over committed fixture manifests in a new `scripts/fusecheck-fixtures/` directory, the mold of `scripts/kinematics-fixtures/` (#620) — not a new `--fusecheck-selftest` flag inside `gate.sh`. The parsing seam moves with it: the fusecheck runner is **extracted** from `gate.sh` into `scripts/fusecheck-check.sh` verbatim, and `gate.sh` calls the extracted runner — so the selftest exercises the one parser `gate.sh` actually runs, not a copy of it (a selftest over a copy could stay green while the seam regressed, which is exactly the gap this issue files).

**Acceptance criteria** (done = every box checked, verified not asserted)
- [ ] AC1 — fixtures: a tiny fixture design renders a **separable two-body** part and a **known-fused** one (plus whatever third shape the above-max row needs); body counts verified by running `fusecheck` on the exported STLs directly, so the manifest expectations are anchored to measured geometry, not to what the harness reports.
- [ ] AC2 — legacy `assert <stl> <min>`: passes on the separable part; **WARNs** (exit 3, too few) on the fused part — the run continues.
- [ ] AC3 — two-sided `assert <stl> <min> <max>`: passes inside the bound; **hard-FAILs** (exit nonzero) when the count exceeds `max`.
- [ ] AC4 — `assert <stl> =N`: exact-count row passes at N.
- [ ] AC5 — malformed bounds (`max < min`, and a non-numeric operand): the malformed **line itself** FAILs the manifest parse.
- [ ] AC6 — exit-code mapping pinned both directions by the rows above: exit 3 (too few) is never a hard FAIL, exit 4 (too many) is never downgraded to WARN.
- [ ] AC7 — `check.sh` runs the selftest, and every negative row is asserted to fire: the selftest exits nonzero if any expected WARN / FAIL / malformed-FAIL verdict fails to occur (negative controls in the #620 mold, not just happy-path greens).

**Touches:** `scripts/fusecheck-check.sh` (new), `scripts/fusecheck-fixtures/**` (new — fixture `.scad`, manifests, README), `scripts/check.sh`, `scripts/gate.sh` (the extraction + the call that replaces it), `CLAUDE.md` (the `scripts/` bullet — `docs-check.sh` requires it to name every file in `scripts/`), `README.md` (the scripts list — same docs-drift gate), `.github/workflows/ci.yml` (the `scad-check` / `scad-check-nightly` jobs gain the `actions/setup-python` + `pip install -e tools/printcheck` steps `render-gate` already carries — the selftest measures geometry through printcheck, and a skipped selftest is exactly the silent green this issue exists to close)

**Explicitly not in scope:** any change to `tools/printcheck`'s fusecheck logic itself (a defect found while building this gets a new issue, linked from the PR — this PR adds tests only); the six existing designs' `ci.fusecheck` manifests; `gate.sh`'s runtime behavior beyond the verbatim extraction (exercised read-only); the kinematics fixtures.

**Base:** stacked on open PR **#618**'s head (`claude/issue-612-stencil-fusecheck`) — the two-sided/`=N` seam this fixture tests only exists there, not on `main`; retargets to `main` when #618 merges.

**Comment by shaiss** [comment]
🚢 SHIP-LOCK — shipping this as one PR.

**Taking over after the withdrawal** ([claim posted 2026-09-14T14:12:28Z](https://github.com/shaiss/print-bench/issues/627#issuecomment-5692628966), [withdrawn 16:11Z](https://github.com/shaiss/print-bench/issues/627#issuecomment-5702842866) when the scheduled run died without pushing a branch — the second such death). No `claude/issue-627-*` branch, no open closing PR — the issue is free. The contract below was frozen on this thread before any diff existed and is re-frozen **unchanged**, all three posted amendments folded in ([stack on #618](https://github.com/shaiss/print-bench/issues/627#issuecomment-5655598055), [Touches widened to `scripts/gate.sh` + `README.md`](https://github.com/shaiss/print-bench/issues/627#issuecomment-5655742973), [`.github/workflows/ci.yml` added](https://github.com/shaiss/print-bench/issues/627#issuecomment-5683925491)).

**Chosen approach:** the issue's second named form — a dedicated `scripts/fusecheck-check.sh --selftest` that `check.sh` calls (matching the repo's existing `*-check.sh --selftest` convention), driving the **real** `gate.sh` fusecheck pass end-to-end over committed fixture manifests in a new `scripts/fusecheck-fixtures/` directory, the mold of `scripts/kinematics-fixtures/` (#620) — not a new `--fusecheck-selftest` flag inside `gate.sh`. The parsing seam moves with it: the fusecheck runner is **extracted** from `gate.sh` into `scripts/fusecheck-check.sh` verbatim, and `gate.sh` calls the extracted runner — so the selftest exercises the one parser `gate.sh` actually runs, not a copy of it (a selftest over a copy could stay green while the seam regressed, which is exactly the gap this issue files).

**Acceptance criteria** (done = every box checked, verified not asserted)
- [ ] AC1 — fixtures: a tiny fixture design renders a **separable two-body** part and a **known-fused** one (plus whatever third shape the above-max row needs); body counts verified by running `fusecheck` on the exported STLs directly, so the manifest expectations are anchored to measured geometry, not to what the harness reports.
- [ ] AC2 — legacy `assert <stl> <min>`: passes on the separable part; **WARNs** (exit 3, too few) on the fused part — the run continues.
- [ ] AC3 — two-sided `assert <stl> <min> <max>`: passes inside the bound; **hard-FAILs** (exit nonzero) when the count exceeds `max`.
- [ ] AC4 — `assert <stl> =N`: exact-count row passes at N.
- [ ] AC5 — malformed bounds (`max < min`, and a non-numeric operand): the malformed **line itself** FAILs the manifest parse.
- [ ] AC6 — exit-code mapping pinned both directions by the rows above: exit 3 (too few) is never a hard FAIL, exit 4 (too many) is never downgraded to WARN.
- [ ] AC7 — `check.sh` runs the selftest, and every negative row is asserted to fire: the selftest exits nonzero if any expected WARN / FAIL / malformed-FAIL verdict fails to occur (negative controls in the #620 mold, not just happy-path greens).

**Touches:** `scripts/fusecheck-check.sh` (new), `scripts/fusecheck-fixtures/**` (new — fixture `.scad`, manifests, README), `scripts/check.sh`, `scripts/gate.sh` (the extraction + the call that replaces it), `CLAUDE.md` (the `scripts/` bullet — `docs-check.sh` requires it to name every file in `scripts/`), `README.md` (the scripts list — same docs-drift gate), `.github/workflows/ci.yml` (the `scad-check` / `scad-check-nightly` jobs gain the `actions/setup-python` + `pip install -e tools/printcheck` steps `render-gate` already carries — the selftest measures geometry through printcheck, and a skipped selftest is exactly the silent green this issue exists to close)

**Explicitly not in scope:** any change to `tools/printcheck`'s fusecheck logic itself (a defect found while building this gets a new issue, linked from the PR — this PR adds tests only); the six existing designs' `ci.fusecheck` manifests; `gate.sh`'s runtime behavior beyond the verbatim extraction (exercised read-only); the kinematics fixtures.

**Base:** stacked on open PR **#618**'s head (`claude/issue-612-stencil-fusecheck`) — the two-sided/`=N` seam this fixture tests only exists there, not on `main`; retargets to `main` when #618 merges.

**Comment by shaiss** [comment]
🚢 SHIP-LOCK — shipping this as one PR.

**Taking over the stale claim** ([posted 2026-09-14T19:28:00Z](https://github.com/shaiss/print-bench/issues/627#issuecomment-5669582726)): ~6 h old with **no** `claude/issue-627-*` branch on the remote and **no** open PR closing this issue — the same died-before-pushing signature that released the two claims before it (root cause filed as #670: the stacked checkout ran the pre-#538 lock-cleanup). This is an attended `/ship-issue 627` run; it withdraws its own lock if it stops before pushing a branch, so it cannot strand the issue.

The contract below was frozen on this thread before any diff existed ([original 2026-09-13T19:31:49Z](https://github.com/shaiss/print-bench/issues/627#issuecomment-5655577009)) and is re-frozen **unchanged**, all three posted amendments folded in ([stack on #618](https://github.com/shaiss/print-bench/issues/627#issuecomment-5655598055), [Touches widened to `scripts/gate.sh` + `README.md`](https://github.com/shaiss/print-bench/issues/627#issuecomment-5655742973), [`.github/workflows/ci.yml` added](https://github.com/shaiss/print-bench/issues/627#issuecomment-5683925491)).

**Chosen approach:** the issue's second named form — a dedicated `scripts/fusecheck-check.sh --selftest` that `check.sh` calls (matching the repo's existing `*-check.sh --selftest` convention), driving the **real** `gate.sh` fusecheck pass end-to-end over committed fixture manifests in a new `scripts/fusecheck-fixtures/` directory, the mold of `scripts/kinematics-fixtures/` (#620) — not a new `--fusecheck-selftest` flag inside `gate.sh`. The parsing seam moves with it: the fusecheck runner is **extracted** from `gate.sh` into `scripts/fusecheck-check.sh` verbatim, and `gate.sh` calls the extracted runner — so the selftest exercises the one parser `gate.sh` actually runs, not a copy of it (a selftest over a copy could stay green while the seam regressed, which is exactly the gap this issue files).

**Acceptance criteria** (done = every box checked, verified not asserted)
- [ ] AC1 — fixtures: a tiny fixture design renders a **separable two-body** part and a **known-fused** one (plus whatever third shape the above-max row needs); body counts verified by running `fusecheck` on the exported STLs directly, so the manifest expectations are anchored to measured geometry, not to what the harness reports.
- [ ] AC2 — legacy `assert <stl> <min>`: passes on the separable part; **WARNs** (exit 3, too few) on the fused part — the run continues.
- [ ] AC3 — two-sided `assert <stl> <min> <max>`: passes inside the bound; **hard-FAILs** (exit nonzero) when the count exceeds `max`.
- [ ] AC4 — `assert <stl> =N`: exact-count row passes at N.
- [ ] AC5 — malformed bounds (`max < min`, and a non-numeric operand): the malformed **line itself** FAILs the manifest parse.
- [ ] AC6 — exit-code mapping pinned both directions by the rows above: exit 3 (too few) is never a hard FAIL, exit 4 (too many) is never downgraded to WARN.
- [ ] AC7 — `check.sh` runs the selftest, and every negative row is asserted to fire: the selftest exits nonzero if any expected WARN / FAIL / malformed-FAIL verdict fails to occur (negative controls in the #620 mold, not just happy-path greens).

**Touches:** `scripts/fusecheck-check.sh` (new), `scripts/fusecheck-fixtures/**` (new — fixture `.scad`, manifests, README), `scripts/check.sh`, `scripts/gate.sh` (the extraction + the call that replaces it), `CLAUDE.md` (the `scripts/` bullet — `docs-check.sh` requires it to name every file in `scripts/`), `README.md` (the scripts list — same docs-drift gate), `.github/workflows/ci.yml` (the `scad-check` / `scad-check-nightly` jobs gain the `actions/setup-python` + `pip install -e tools/printcheck` steps `render-gate` already carries — the selftest measures geometry through printcheck, and a skipped selftest is exactly the silent green this issue exists to close)

**Explicitly not in scope:** any change to `tools/printcheck`'s fusecheck logic itself (a defect found while building this gets a new issue, linked from the PR — this PR adds tests only); the six existing designs' `ci.fusecheck` manifests; `gate.sh`'s runtime behavior beyond the verbatim extraction (exercised read-only); the kinematics fixtures.

**Base:** stacked on open PR **#618**'s head (`claude/issue-612-stencil-fusecheck`) — the two-sided/`=N` seam this fixture tests only exists there, not on `main`; retargets to `main` when #618 merges.

**Comment by shaiss** [comment]
📦 **Delivered via stack — no further PR needed.** Status note from a `/ship-issue 627` run that found the work already shipped:

- **#679** ("Closes #627", contract [claimed 2026-09-15T01:42Z](https://github.com/shaiss/print-bench/issues/627#issuecomment-5673385714) before any diff) was **merged today into #618's head** (`claude/issue-612-stencil-fusecheck`, commit `30f37b58`). Verified on that branch: `scripts/fusecheck-check.sh` + the seven `scripts/fusecheck-fixtures/` files exist; `check.sh` runs the selftest (step 8); `gate.sh` sources the extracted `fusecheck_gate` and calls it per design. All seven ACs were checked with measured evidence on the PR.
- The **2026-09-15 SHIP-LOCK above is delivered, not stale** — its run pushed the branch and PR. It should stay standing (unedited) until this issue closes: it is what keeps the burn selector from re-selecting #627 and spawning a duplicate PR.
- **Close-out trap:** merging #679 into a non-default branch did **not** auto-close this issue, and merging #618 into `main` won't either (stacked `Closes` references don't propagate). When #618 lands on `main`, close this issue as completed referencing #679 — or the owner can close it earlier if "merged into the open stack parent" already counts as done.

Separately noted (not this issue's scope, recorded here only because it gates the above): **#618 is currently `CONFLICTING` with `main`** and needs a `main` merge-in before any of this reaches the default branch.

This run ships nothing — opening a second PR for an already-merged deliverable would duplicate the diff sitting on #618's branch.
